import type { Metadata } from "next";
import { getServerSideHTMLReactElements } from "@xo-union/tk-ui-essentials/server";

import { Inter } from "next/font/google";

import { ENV } from "@env";

import "@xo-union/tk-ui-essentials";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const serverSideHTML = getServerSideHTMLReactElements(); // Default config

  return (
    <html lang="en">
      <head>{serverSideHTML.head}</head>

      <body className={inter.className}>
        {serverSideHTML.body}
        {children}
      </body>
    </html>
  );
}
